Shopfb.create!(:shopinfo_id => "1",:fbshopname => "ミュゼプラチナム",:fbtitle => "お得意様",:fbcomment => "価格の推移をずっと見てきましたが、今回かなり下がったので購入しました。
私は首のコリが酷いため、効果があればと思い購入しました。",:auther => "hebochi",:fbrank => 4,:ages => "20代前半",:jobs => "OL")
Shopfb.create!(:shopinfo_id => "1",:fbshopname => "ミュゼプラチナム",:fbtitle => "気持ちぃぃ",:fbcomment => "首こりがひどかったのですが、これを使用することで、大変楽になりました。
とってもいい買い物ができたと思います。",:auther => "スリーパー",:fbrank => 5,:ages => "30代前半",:jobs => "OL")
Shopfb.create!(:shopinfo_id => "1",:fbshopname => "ミュゼプラチナム",:fbtitle => "おすすめです",:fbcomment => "価格の推移をずっと見てきましたが、今回かなり下がったので購入しました。
私は首のコリが酷いため、効果があればと思い購入しました。",:auther => "よしこ",:fbrank => 4,:ages => "30代前半",:jobs => "OL")
Shopfb.create!(:shopinfo_id => "2",:fbshopname => "銀座カラー",:fbtitle => "安くてよかった",:fbcomment => "首こりがひどかったのですが、これを使用することで、大変楽になりました。
とってもいい買い物ができたと思います。",:auther => "Customer",:fbrank => 3,:ages => "20代後半",:jobs => "OL")
Shopfb.create!(:shopinfo_id => "2",:fbshopname => "銀座カラー",:fbtitle => "勧誘がなかった",:fbcomment => "価格の推移をずっと見てきましたが、今回かなり下がったので購入しました。
私は首のコリが酷いため、効果があればと思い購入しました。",:auther => "ユーザー",:fbrank => 4,:ages => "20代後半",:jobs => "OL")
Shopfb.create!(:shopinfo_id => "2",:fbshopname => "銀座カラー",:fbtitle => "お財布に優しい",:fbcomment => "首こりがひどかったのですが、これを使用することで、大変楽になりました。
とってもいい買い物ができたと思います。",:auther => "Beauty",:fbrank => 5,:ages => "10代後半",:jobs => "学生")
Shopfb.create!(:shopinfo_id => "3",:fbshopname => "脱毛ラボ",:fbtitle => "気遣いが素晴らしい",:fbcomment => "価格の推移をずっと見てきましたが、今回かなり下がったので購入しました。
私は首のコリが酷いため、効果があればと思い購入しました。",:auther => "たらこ",:fbrank => 5,:ages => "20代後半",:jobs => "ショップ店員")
Shopfb.create!(:shopinfo_id => "3",:fbshopname => "脱毛ラボ",:fbtitle => "勧誘なし！",:fbcomment => "首こりがひどかったのですが、これを使用することで、大変楽になりました。
とってもいい買い物ができたと思います。",:auther => "山田花子",:fbrank => 5,:ages => "30代前半",:jobs => "美容関係")
Shopfb.create!(:shopinfo_id => "3",:fbshopname => "脱毛ラボ",:fbtitle => "寝てしまった",:fbcomment => "価格の推移をずっと見てきましたが、今回かなり下がったので購入しました。
私は首のコリが酷いため、効果があればと思い購入しました。",:auther => "まゆみん",:fbrank => 4,:ages => "30代後半",:jobs => "ショップ店員")
Shopfb.create!(:shopinfo_id => "4",:fbshopname => "シースリー",:fbtitle => "おすすめできるかな",:fbcomment => "首こりがひどかったのですが、これを使用することで、大変楽になりました。
とってもいい買い物ができたと思います。",:auther => "りさりさ",:fbrank => 5,:ages => "20代前半",:jobs => "OL")
Shopfb.create!(:shopinfo_id => "4",:fbshopname => "シースリー",:fbtitle => "大満足",:fbcomment => "価格の推移をずっと見てきましたが、今回かなり下がったので購入しました。
私は首のコリが酷いため、効果があればと思い購入しました。",:auther => "Hirokomix",:fbrank => 4,:ages => "20代後半",:jobs => "OL")
