# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebbced25bdd3147fc14e54e7ab613b611c1bfdff5951bf3bdfd1492f675247d1ff17f5f21aefe2a821504eb61ffe9d86a3feb7ffae56a343d72db35a9d59b3d5

staging:
  secret_key_base: ebbced25bdd3147fc14e54e7ab613b611c1bfdff5951bf3bdfd1492f675247d1ff17f5f21aefe2a821504eb61ffe9d86a3feb7ffae56a343d72db35a9d59b3d5


test:
  secret_key_base: 45d21e6678f635c73d0eb8eb5f0a6005026ca9248764926ae879bb719ac3f447b5be52b5bd2c27392e86e703ffe66d67fcaf3cc582d71144cbba180cb4cb250b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
