Shopinfo.create!(:shopname => "ミュゼプラチナム",:company => "株式会社ミュゼプラチナム",:affili => "https://track.affiliate-b.com/visit.php?guid=ON&a=M55347-h261040n&p=U445860X",:ranking => 5,:recommend => "ミュゼは美容脱毛専門サロン店舗数・売上、美容脱毛サロン顧客満足度でNo.1を獲得。安心・便利・通いやすいサービスで、お客さまに選ばれています。",:shoptype => "エステサロン",:treattype => "S.S.C.方式(スムーススキンコントロール方式)",:body => "全身",:machine => "確認中",:campaign => "Enjoy, Girlsキャンペーン",:price1 => "全身脱毛が月額7,000円(税込)から",:price2 => "全身脱毛が月額7,000円(税込)から",:price3 => "全身脱毛が月額7,000円(税込)から",:pic1 => "http://musee-pla.com/lp/mo/lpBg/img/top_bg_b.jpg",:pic2 => "",:pic3 => "",:pic4 => "",:pic5 => "")
Shopinfo.create!(:shopname => "銀座カラー",:company => "株式会社エム・シーネットワークスジャパン",:affili => "https://track.affiliate-b.com/visit.php?guid=ON&a=i2595j-d95060z&p=U445860X",:ranking => 5,:recommend => "銀座カラーではIPL脱毛という、光のエネルギーがムダ毛に直接作用する脱毛方法を採用しています。さらに、オリジナル保湿ケア『美肌潤美』（オプション）を施術後におこなっております。美肌効果と脱毛効果を同時に高め、格段に違う効果を実感していただけます。",:shoptype => "エステサロン",:treattype => "IPL脱毛(光脱毛)",:body => "全身",:machine => "確認中",:campaign => "プレミアムファストパス:新全身脱毛「初月+2ヶ月目分0円」",:price1 => "全身脱毛が月額7,000円(税込)から",:price2 => "全身脱毛が月額7,000円(税込)から",:price3 => "全身脱毛が月額7,000円(税込)から",:pic1 => "http://musee-pla.com/lp/mo/lpBg/img/top_bg_b.jpg",:pic2 => "",:pic3 => "",:pic4 => "",:pic5 => "")
Shopinfo.create!(:shopname => "脱毛ラボ",:company => "株式会社セドナエンタープライズ",:affili => "https://track.affiliate-b.com/visit.php?guid=ON&a=44395S-u2567941&p=U445860X",:ranking => 5,:recommend => "脱毛ラボでは、「S.S.C.脱毛」を採用！ 従来のキセノンライトによる脱毛とは異なる「クリプトンライト」によるS.S.C脱毛だから、お肌に直接的なダメージを与えません！さらに専用ジェルに含まれるフィリニーブ成分がお肌に浸透します。",:shoptype => "エステサロン",:treattype => "S.S.C.方式(スムーススキンコントロール方式)",:body => "全身",:machine => "M.S.F.T.クリプトン、P.Sクリプトン、クリプトンSEV",:campaign => "月額制全身脱毛プラン 3,980円/月額 が4ヶ月無料！",:price1 => "全身脱毛が月額7,000円(税込)から",:price2 => "全身脱毛が月額7,000円(税込)から",:price3 => "全身脱毛が月額7,000円(税込)から",:pic1 => "http://musee-pla.com/lp/mo/lpBg/img/top_bg_b.jpg",:pic2 => "",:pic3 => "",:pic4 => "",:pic5 => "")
Shopinfo.create!(:shopname => "シースリー",:company => "株式会社ビューティースリー",:affili => "http://c-3-esthe.com/lp002/?f=4",:ranking => 5,:recommend => "シースリーでは日本人女性のために開発された最新の超光速脱毛機C3 GTRで全身最短45分！脱毛完了まで期限切れなしの脱毛品質保証。納得いくまで何度でも利用できます！",:shoptype => "エステサロン",:treattype => "光脱毛",:body => "全身",:machine => "C3 GTR",:campaign => "全身永久保障プラン月額7,500円が最大2か月0円",:price1 => "全身脱毛が月額7,000円(税込)から",:price2 => "全身脱毛が月額7,000円(税込)から",:price3 => "全身脱毛が月額7,000円(税込)から",:pic1 => "http://musee-pla.com/lp/mo/lpBg/img/top_bg_b.jpg",:pic2 => "",:pic3 => "",:pic4 => "",:pic5 => "")
Shopinfo.create!(:shopname => "エターナルラビリンス",:company => "株式会社グロワール・ブリエ東京",:affili => "https://track.affiliate-b.com/visit.php?guid=ON&a=S4952T-O264304o&p=U445860X",:ranking => 5,:recommend => "設立10年を超え、あの有名人も絶賛する全身脱毛サロン。エタラビ。
 TVでもお馴染みの脱毛サロンとして口コミを含めた会員は10万人を突破。
 他サロンとの大きな違いは「お客様とのコミュニケーション」を一番大切に考えていることです。
 無料カウンセリングから始まり、脱毛の正しい知識をお伝えしながらご納得のうえ施術に入ります。結果としてリピーター率は80%を超えお客様の満足度も高いものとなります。
 創業以来最も力を入れている『全身脱毛』などお客様のニーズに応じたコースを取りそろえています。輝かしい女性の価値を作る「愛され美肌脱毛」を目指しています。",:shoptype => "エステサロン",:treattype => "美容ライト脱毛",:body => "全身",:machine => "純国産美容脱毛機PLASMA More",:campaign => "真360°脱毛 全身全部位を360°脱毛。通常月額9,500円が今なら初月から3か月分が0円",:price1 => "全身脱毛が月額7,000円(税込)から",:price2 => "全身脱毛が月額7,000円(税込)から",:price3 => "全身脱毛が月額7,000円(税込)から",:pic1 => "http://musee-pla.com/lp/mo/lpBg/img/top_bg_b.jpg",:pic2 => "",:pic3 => "",:pic4 => "",:pic5 => "")
Shopinfo.create!(:shopname => "キレイモ",:company => "株式会社ヴィエリス",:affili => "https://track.affiliate-b.com/visit.php?guid=ON&a=N6315q-A250652A&p=U445860X",:ranking => 4,:recommend => "全身脱毛サロンキレイモは、業界口コミNO.01！だからタレントさんや読者モデルのみなさんに多数ご来店いただいております。ご来店の様子は随時、キレイモ公式twitterでも発信していますので、是非ご覧になってください。",:shoptype => "エステサロン",:treattype => "S.S.C.方式(スムーススキンコントロール方式)",:body => "全身",:machine => "確認中",:campaign => "全身脱毛33カ所が通常9500円のところが、初月0円（税込）",:price1 => "全身脱毛が月額7,000円(税込)から",:price2 => "全身脱毛が月額7,000円(税込)から",:price3 => "全身脱毛が月額7,000円(税込)から",:pic1 => "http://musee-pla.com/lp/mo/lpBg/img/top_bg_b.jpg",:pic2 => "",:pic3 => "",:pic4 => "",:pic5 => "")
Shopinfo.create!(:shopname => "エステティックTBC",:company => "TBCグループ株式会社",:affili => "https://track.affiliate-b.com/visit.php?guid=ON&a=N6315q-A250652A&p=U445860X",:ranking => 4,:recommend => "1本1本確実に処理していく「TBCスーパー脱毛」。広範囲を一気に処理する「TBCライト脱毛」。その2つのメリットを組み合わせた「TBCスーパー＆ライト脱毛」をご用意。あなたにぴったりの脱毛方法が見つかります。",:shoptype => "エステサロン",:treattype => "美容電気脱毛、美容ライト脱毛",:body => "全身",:machine => "情報なし",:campaign => "両ワキ脱毛。スーパー＆ライト１回体験プランが初めて割価格の600円(税込)",:price1 => "全身脱毛が月額7,000円(税込)から",:price2 => "全身脱毛が月額7,000円(税込)から",:price3 => "全身脱毛が月額7,000円(税込)から",:pic1 => "http://musee-pla.com/lp/mo/lpBg/img/top_bg_b.jpg",:pic2 => "",:pic3 => "",:pic4 => "",:pic5 => "")
Shopinfo.create!(:shopname => "ラ・ヴォーグ",:company => "株式会社ダイシン",:affili => "https://track.affiliate-b.com/visit.php?guid=ON&a=a6684E-Z243974d&p=U445860X",:ranking => 4,:recommend => "ラ・ヴォーグの脱毛は、脱毛の効果だけではなく脱毛しながらお肌のコラーゲンを再生し、美肌に導く、コラーゲン美肌脱毛を採用しています。低価格で提供できる理由は、「最新の脱毛器の代理店をしていることで、大変高価なランニングコストを抑えることが可能になったこと」や、「最新の技術を使用することで、施術時間がスピードアップし、短時間で多くのお客様を施術出来るようになったこと」です。",:shoptype => "エステサロン",:treattype => "光脱毛",:body => "全身",:machine => "最新で安全で効果の高い純国産脱毛器・ＬＶＳ（エルブイエス）",:campaign => "顔・VIOを含む全身脱毛55部位。月額3,200円が今なら4か月間0円。",:price1 => "全身脱毛が月額7,000円(税込)から",:price2 => "全身脱毛が月額7,000円(税込)から",:price3 => "全身脱毛が月額7,000円(税込)から",:pic1 => "http://musee-pla.com/lp/mo/lpBg/img/top_bg_b.jpg",:pic2 => "",:pic3 => "",:pic4 => "",:pic5 => "")
Shopinfo.create!(:shopname => "エピレ",:company => "株式会社シュプレイムルミナス",:affili => "https://track.affiliate-b.com/visit.php?guid=ON&a=L4711u-2220810F&p=U445860X",:ranking => 4,:recommend => "TBCがプロデュースする，お客様の声から生まれた脱毛専門サロン「エピレ」。Ｓパーツはもちもん，下記Ｌパーツも2,400円で体験が可能！
 エピレ店舗だけでなく全国４７都道府県のエステティックＴＢＣでも施術可能です！",:shoptype => "エステサロン",:treattype => "光脱毛",:body => "全身",:machine => "フェリークFv4",:campaign => "ハッピーつるスベキャンペーン。両ワキ+Vライン脱毛6回 通常販売価格 28512円がなんと700円(97%OFF)",:price1 => "全身脱毛が月額7,000円(税込)から",:price2 => "全身脱毛が月額7,000円(税込)から",:price3 => "全身脱毛が月額7,000円(税込)から",:pic1 => "http://musee-pla.com/lp/mo/lpBg/img/top_bg_b.jpg",:pic2 => "",:pic3 => "",:pic4 => "",:pic5 => "")
Shopinfo.create!(:shopname => "ラットタット",:company => "ミスプレミアム株式会社",:affili => "https://track.affiliate-b.com/visit.php?guid=ON&a=V7221w-B239472x&p=U445860X",:ranking => 3,:recommend => "2015年5月に新規オープンの女性専用の脱毛サロンです。
 月額6,800円で50部位が脱毛できる！
 10年以上のキャリアを持つ脱毛のプロもたくさんおります。技術力に自信があります！高級ホテル品質のタオル類を1回使うごとにプロのクリーニングにお願いしています。施術前後に使用する保湿ローションは医療機関と一緒に開発した独自のもの。
 これまでにない脱毛＆美肌効果を体感ください。",:shoptype => "エステサロン",:treattype => "確認中",:body => "全身",:machine => "確認中",:campaign => "全身50部位を安心の月額制で完全脱毛。通常価格6,500円が今なら初月から2か月分0円。",:price1 => "全身脱毛が月額7,000円(税込)から",:price2 => "全身脱毛が月額7,000円(税込)から",:price3 => "全身脱毛が月額7,000円(税込)から",:pic1 => "http://musee-pla.com/lp/mo/lpBg/img/top_bg_b.jpg",:pic2 => "",:pic3 => "",:pic4 => "",:pic5 => "")

 Shopbranch.create!(:shopinfo_id => "1",:shopname => "ミュゼプラチナム",:branchname => "渋谷アネックス店",:address => "東京都渋谷区渋谷1丁目12-7 CR-VITEビル4F",:tel => "",:starthour => "11:00",:endhour => "21:00",:e_starthour => "",:e_endhour => "",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "渋谷",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "渋谷区",:access => "東急線・地下鉄各線 渋谷駅(11番出口)から徒歩2分<br>JR各線 渋谷駅(宮益坂出口)から徒歩3分<br>＊渋谷郵便局 隣り",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "1",:shopname => "ミュゼプラチナム",:branchname => "渋谷店",:address => "東京都渋谷区渋谷1丁目14-14 TK渋谷東口ビル5F",:tel => "",:starthour => "11:00",:endhour => "21:00",:e_starthour => "",:e_endhour => "",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "渋谷",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "渋谷区",:access => "東急線・地下鉄各線「渋谷駅」11番出口徒歩1分<br>JR各線「渋谷駅」の宮益坂出口徒歩3分",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "1",:shopname => "ミュゼプラチナム",:branchname => "恵比寿店",:address => "東京都渋谷区恵比寿1丁目12-1 CRD Ebisu 1stビル6F",:tel => "",:starthour => "11:00",:endhour => "21:00",:e_starthour => "",:e_endhour => "",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "恵比寿",:train2 => "日比谷線",:station2 => "恵比寿",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "渋谷区",:access => "JR各線「恵比寿駅」東口　徒歩3分<br>東京メトロ日比谷線「恵比寿駅」1番出口 徒歩5分<br>※1階にびっくり寿司があるビルです。",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "1",:shopname => "ミュゼプラチナム",:branchname => "目黒店",:address => "東京都品川区上大崎2丁目16-5 目黒ステーションサイドビル7F",:tel => "",:starthour => "10:00",:endhour => "20:00",:e_starthour => "",:e_endhour => "",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "目黒",:train2 => "目黒線",:station2 => "目黒",:train3 => "南北線",:station3 => "目黒",:area => "関東",:prefec => "東京都",:city => "品川区",:access => "JR山手線 目黒駅(東口)から徒歩1?2分<br>東急目黒線・東京メトロ南北線・都営地下鉄三田線 目黒駅から徒歩3分",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "1",:shopname => "ミュゼプラチナム",:branchname => "五反田店",:address => "東京都品川区東五反田5丁目27-5 5セントラルビル6F",:tel => "",:starthour => "10:00",:endhour => "20:00",:e_starthour => "",:e_endhour => "",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "五反田",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "品川区",:access => "JR山手線 「五反田駅」東口　徒歩1分<br>都営地下鉄浅草線 「五反田駅」A4出口　徒歩1分<br>東急池上線 「五反田駅」　徒歩3分<br>※「富士そば」の右隣のビルです。",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "1",:shopname => "ミュゼプラチナム",:branchname => "アトレ大森店",:address => "東京都大田区大森北1丁目6-16 アトレ大森2 6F",:tel => "",:starthour => "10:00",:endhour => "20:00",:e_starthour => "",:e_endhour => "",:holiday => "休館日と同じ",:latitude => "",:longitude => "",:train => "JR京浜東北線",:station => "大森",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "大田区",:access => "JR京浜東北線「大森駅」東口　徒歩3分",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "1",:shopname => "ミュゼプラチナム",:branchname => "グランデュオ蒲田店",:address => "東京都大田区西蒲田7丁目68-1 グランデュオ蒲田西館9F",:tel => "",:starthour => "10:00",:endhour => "20:00",:e_starthour => "",:e_endhour => "",:holiday => "休館日と同じ",:latitude => "",:longitude => "",:train => "JR京浜東北線",:station => "蒲田",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "大田区",:access => "JR京浜東北線 蒲田駅(西口)直結",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "1",:shopname => "ミュゼプラチナム",:branchname => "自由が丘南口店",:address => "東京都世田谷区奥沢5丁目26-12 自由が丘MERIX4F",:tel => "",:starthour => "10:00",:endhour => "20:00",:e_starthour => "",:e_endhour => "",:holiday => "なし",:latitude => "",:longitude => "",:train => "東急東横線",:station => "自由が丘",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "世田谷区",:access => "東急東横線・大井町線 自由が丘駅(南口)から徒歩2分",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "1",:shopname => "ミュゼプラチナム",:branchname => "吉祥寺店",:address => "東京都武蔵野市吉祥寺本町1丁目13-11 メアリヒト吉祥寺ビル6F",:tel => "",:starthour => "10:00",:endhour => "20:00",:e_starthour => "",:e_endhour => "",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "吉祥寺",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "武蔵野市",:access => "各線 吉祥寺駅(北口)から徒歩3分<br>※「吉祥寺店」と「吉祥寺“北口”店」の2つの店舗がございます。<br>名前がよく似ていますので、ご来店の際はお間違えのないようお気をつけてお越しくださいませ。",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "1",:shopname => "ミュゼプラチナム",:branchname => "吉祥寺北口店",:address => "東京都武蔵野市吉祥寺本町1丁目1-12 第2小野山ビル6F",:tel => "",:starthour => "10:00",:endhour => "20:00",:e_starthour => "",:e_endhour => "",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "吉祥寺",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "武蔵野市",:access => "各線 吉祥寺駅(北口)から徒歩2分<br>※吉祥寺店と吉祥寺“北口”店の2つの店舗がございます。<br>名前がよく似ていますので、ご来店の際はお間違えのないようお気をつけてお越しくださいませ。",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "1",:shopname => "ミュゼプラチナム",:branchname => "立川南口店",:address => "東京都立川市柴崎町3丁目7-24 MYビル4F",:tel => "",:starthour => "10:00",:endhour => "20:00",:e_starthour => "",:e_endhour => "",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "立川",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "立川市",:access => "JR各線「立川駅」南口 徒歩3分<br>多摩都市モノレール線「立川南駅」出入口1 徒歩2分",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "1",:shopname => "ミュゼプラチナム",:branchname => "立川北口店",:address => "東京都立川市曙町2丁目6-10 ナカムラビル5F",:tel => "",:starthour => "10:00",:endhour => "20:00",:e_starthour => "",:e_endhour => "",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "立川",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "立川市",:access => "JR各線 立川駅(北口)から徒歩2分",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "1",:shopname => "ミュゼプラチナム",:branchname => "八王子東急スクエア店",:address => "東京都八王子市旭町9-1 東急スクエア10F",:tel => "",:starthour => "10:00",:endhour => "20:00",:e_starthour => "",:e_endhour => "",:holiday => "休館日と同じ",:latitude => "",:longitude => "",:train => "JR線",:station => "八王子",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "八王子市",:access => "JR各線「八王子駅」北口　徒歩3分",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "1",:shopname => "ミュゼプラチナム",:branchname => "クロスガーデン多摩店",:address => "東京都多摩市落合2丁目33 クロスガーデン多摩3F",:tel => "",:starthour => "10:00",:endhour => "20:00",:e_starthour => "",:e_endhour => "",:holiday => "なし",:latitude => "",:longitude => "",:train => "小田急線",:station => "多摩センター",:train2 => "京王線",:station2 => "多摩センター",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "多摩市",:access => "京王線・小田急線「多摩センター駅」中央口 徒歩15分<br>多摩都市モノレール「多摩センター駅」出入口4　徒歩12分",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "1",:shopname => "ミュゼプラチナム",:branchname => "町田109店",:address => "東京都町田市原町田6-8-1 109町田4F",:tel => "",:starthour => "10:30",:endhour => "20:30",:e_starthour => "",:e_endhour => "",:holiday => "元旦",:latitude => "",:longitude => "",:train => "JR横浜線",:station => "町田",:train2 => "小田急線",:station2 => "町田",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "町田市",:access => "JR横浜線「町田駅」北口　徒歩1分<br>小田急線「町田駅」西口　徒歩3分",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "1",:shopname => "ミュゼプラチナム",:branchname => "グラン町田レガロ店",:address => "東京都町田市原町田4丁目5-8 いちご町田イーストビル3F",:tel => "",:starthour => "10:00",:endhour => "20:00",:e_starthour => "",:e_endhour => "",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR横浜線",:station => "町田",:train2 => "小田急線",:station2 => "町田",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "町田市",:access => "小田急線 町田駅(東口出口)から徒歩７分<br>JR横浜線 町田駅(中央改札出口)から徒歩5分",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "1",:shopname => "ミュゼプラチナム",:branchname => "町田東急ツインズ店",:address => "東京都町田市原町田6丁目4-1 町田東急ツインズウエスト7F",:tel => "",:starthour => "10:00",:endhour => "21:00",:e_starthour => "",:e_endhour => "",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR横浜線",:station => "町田",:train2 => "小田急線",:station2 => "町田",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "町田市",:access => "JR横浜線「町田駅」北口から徒歩3分<br>小田急線「町田駅」西口から徒歩4分",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "2",:shopname => "銀座カラー",:branchname => "銀座プレミア店",:address => "東京都中央区銀座5-3-13 GINZA SS 85ビル 4F",:tel => "",:starthour => "12:00",:endhour => "21:00",:e_starthour => "10:00",:e_endhour => "19:00",:holiday => "なし",:latitude => "",:longitude => "",:train => "丸ノ内線",:station => "銀座",:train2 => "銀座線",:station2 => "銀座",:train3 => "日比谷線",:station3 => "銀座",:area => "関東",:prefec => "東京都",:city => "中央区",:access => "地下鉄銀座駅（丸ノ内線・銀座線・日比谷線）B9出口より徒歩2分。JR有楽町駅からも徒歩約5分です。数寄屋橋交差点からは外堀通りを新橋駅方面へ進み、1つ目の信号・銀座西5丁目の角のひとつ手前にある「GINZA SS 85ビル」4階です。",:sheet => "13",:info => "空気を清浄する漆喰（しっくい）の壁、モダンフレンチがコンセプトのチェアやインテリアを使っている銀座プレミア店。ワキはもちろん、顔やVIO、全身脱毛も人気で、リラックスしながらきれいに脱毛できます。")
 Shopbranch.create!(:shopinfo_id => "2",:shopname => "銀座カラー",:branchname => "新宿東口店",:address => "東京都新宿区新宿 3-17-2 ヒューリック新宿三丁目ビル 4F",:tel => "",:starthour => "12:00",:endhour => "22:30",:e_starthour => "10:00",:e_endhour => "19:00",:holiday => "なし",:latitude => "",:longitude => "",:train => "丸ノ内線",:station => "新宿三丁目",:train2 => "副都心線",:station2 => "新宿三丁目",:train3 => "都営新宿線",:station3 => "新宿三丁目",:area => "関東",:prefec => "東京都",:city => "新宿区",:access => "新宿三丁目駅（丸ノ内線、副都心線、都営新宿線）B5・B6出口より徒歩約30秒。JR新宿駅東口からは新宿通りを四谷方面へ徒歩約5分。人気の有名店が立ち並ぶ新宿三丁目にあるヒューリック新宿三丁目ビル（旧 SHINJUKU GATES）4階です。",:sheet => "14",:info => "JR新宿駅の東口からウィンドウショッピングをしながら歩けばすぐ！清潔感溢れる店内はシャンデリアがあり、高級感溢れる空間です。ワキ脱毛や顔脱毛はもちろん、女子力アップに欠かせないVIO脱毛、全身脱毛も人気です。")
 Shopbranch.create!(:shopinfo_id => "2",:shopname => "銀座カラー",:branchname => "新宿南口店",:address => "東京都渋谷区代々木 2-8-3 新宿GSビル 8F",:tel => "",:starthour => "12:00",:endhour => "21:00",:e_starthour => "10:00",:e_endhour => "19:00",:holiday => "なし",:latitude => "",:longitude => "",:train => "都営新宿線",:station => "新宿",:train2 => "大江戸線",:station2 => "新宿",:train3 => "JR線",:station3 => "新宿",:area => "関東",:prefec => "東京都",:city => "渋谷区",:access => "都営地下鉄新宿駅（都営新宿線・大江戸線）2番出口より徒歩1分。JR新宿駅南口から甲州街道を都庁方面へ進み徒歩2分、1つ目の大きな交差点（西新宿1丁目）南側すぐの「新宿GSビル」8階です。",:sheet => "15",:info => "白をベースに、キラキラ素材とビビッドな色合いの小物を使ったインテリアで、 “大人可愛い”雰囲気が楽しめる新宿南口店。駅からのアクセスは徒歩1分！平日でも休日でも抜群の通いやすさで、顔、ワキ、VIO、全身脱毛まで、気になる部分をストレスフリーで脱毛できます")
 Shopbranch.create!(:shopinfo_id => "2",:shopname => "銀座カラー",:branchname => "新宿西口店",:address => "東京都新宿区西新宿1-4-11 宝ビル 7F",:tel => "",:starthour => "12:00",:endhour => "21:00",:e_starthour => "10:00",:e_endhour => "19:00",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "新宿",:train2 => "大江戸線",:station2 => "新宿西口",:train3 => "南北線",:station3 => "目黒",:area => "関東",:prefec => "東京都",:city => "新宿区",:access => "JR新宿駅西口より徒歩5分、都営地下鉄大江戸線の新宿西口駅D4出口より徒歩2分。JR新宿駅西口からは、新宿警察署方面へ進み、新都心歩道橋下交差点の東側すぐの「宝ビル」7階です。",:sheet => "9",:info => "新宿エリア3店舗の中で一番新しい新宿西口店。仕事帰りにも、休日にも通いやすい脱毛サロンです。東京のメインターミナル新宿駅の各路線から徒歩5分の好立地も人気の理由。全身脱毛はもちろん、ワキ、顔、VIOのフリーチョイス脱毛コースも好評です。")
 Shopbranch.create!(:shopinfo_id => "2",:shopname => "銀座カラー",:branchname => "渋谷109前店",:address => "渋谷区宇田川町26-5 育真ビル 5F",:tel => "",:starthour => "12:00",:endhour => "21:00",:e_starthour => "10:00",:e_endhour => "19:00",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "渋谷",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "渋谷区",:access => "渋谷のランドマーク・109前、道玄坂下交差点すぐの「育真ビル（育真プラザ）」5階。JR渋谷駅ハチ公口改札から徒歩3分。地下鉄（銀座線、半蔵門線、副都心線）、京王井の頭線、東急（東横線、田園都市線）の各線からも便利です。",:sheet => "5",:info => "人気のショップやスポットがいっぱいの渋谷。その中心109前にある、うれしい立地の脱毛サロン・渋谷109前店。駅からわずか3分という抜群のアクセスで、ショッピングがてらに、平日の仕事帰りも、気軽に脱毛できちゃいます。顔脱毛、ワキ脱毛、VIO脱毛、お得な全身脱毛も人気です。")
 Shopbranch.create!(:shopinfo_id => "2",:shopname => "銀座カラー",:branchname => "表参道店",:address => "東京都港区北青山3-10-6 青山パークスビル1F",:tel => "",:starthour => "12:00",:endhour => "21:00",:e_starthour => "10:00",:e_endhour => "19:00",:holiday => "なし",:latitude => "",:longitude => "",:train => "銀座線",:station => "表参道",:train2 => "千代田線",:station2 => "表参道",:train3 => "半蔵門線",:station3 => "表参道",:area => "関東",:prefec => "東京都",:city => "港区",:access => "地下鉄（銀座線、千代田線、半蔵門線）表参道駅B2出口より徒歩1分。表参道交差点から進む場合は、青山通り（246号線）を渋谷方面へ進み表参道駅B2出口手前の小道を右折。ガラス張りのエントランスが目印の「青山パークスビル」1階です。",:sheet => "15",:info => "落ち着いたトーンの中にさりげなく輝きをちりばめた、リッチな雰囲気の表参道店は、銀座カラー初の路面店。青山通りから少し入った小道沿いにあり、通うだけで楽しくなる脱毛サロンです。お得に全身が美しくなる全身脱毛はもちろん、顔、ワキ、VIOの各箇所からも気軽に始められます。")
 Shopbranch.create!(:shopinfo_id => "2",:shopname => "銀座カラー",:branchname => "池袋店",:address => "東京都豊島区南池袋 1-19-4 幸伸ビル 7F",:tel => "",:starthour => "12:00",:endhour => "22:30",:e_starthour => "10:00",:e_endhour => "19:00",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "池袋",:train2 => "有楽町線",:station2 => "池袋",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "豊島区",:access => "JR池袋駅南改札より東口へ出て右方面へ、徒歩3分、1Fがドコモショップの「幸伸ビル」7階です。地下鉄有楽町線池袋駅39番出口、西武池袋線池袋駅南口から徒歩3分、地下鉄丸ノ内線池袋駅42番出口からは徒歩5分。",:sheet => "17",:info => "電車の乗り入れも多く、どこからでもアクセスしやすい池袋駅周辺のサロンだから、ショッピングのついでに、友達と一緒に、気軽につるすべ脱毛できます。ワキや顔はもちろん、女子力アップに欠かせないVIO、全身脱毛も人気です。")
 Shopbranch.create!(:shopinfo_id => "2",:shopname => "銀座カラー",:branchname => "池袋サンシャイン通り店",:address => "東京都豊島区東池袋 1-3-6 山手ビル 7F",:tel => "",:starthour => "12:00",:endhour => "21:00",:e_starthour => "10:00",:e_endhour => "19:00",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "池袋",:train2 => "有楽町線",:station2 => "池袋",:train3 => "東武東上線",:station3 => "池袋",:area => "関東",:prefec => "東京都",:city => "豊島区",:access => "JR池袋駅東口を出てすぐの「山手ビル」7階です。JR池袋駅32番・33番出口から徒歩1分、東武東上線、西武池袋線、地下鉄有楽町線・丸ノ内線・副都心線（東急東横線）の池袋駅から徒歩3〜5分。",:sheet => "10",:info => "池袋駅東口から徒歩3分。駅ナカを通ればわずか徒歩1分の脱毛サロン・池袋サンシャイン通り店。20代前半のスタッフが多く、明るくて親しみやすい雰囲気のサロンです。お得に美しくなれる全身脱毛のほか、顔、ワキ、VIOなどフリーチョイス脱毛も気軽にご相談ください。")
 Shopbranch.create!(:shopinfo_id => "2",:shopname => "銀座カラー",:branchname => "上野広小路店",:address => "東京都台東区上野3-22-4 MOTビル 6F",:tel => "",:starthour => "12:00",:endhour => "21:00",:e_starthour => "10:00",:e_endhour => "19:00",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "御徒町",:train2 => "銀座線",:station2 => "上野広小路",:train3 => "大江戸線",:station3 => "上野御徒町",:area => "関東",:prefec => "東京都",:city => "台東区",:access => "JR山手線・御徒町駅南口から徒歩2分、「MOTビル」6階です。地下鉄銀座線上野広小路駅、都営地下鉄大江戸線上野御徒町駅からは徒歩5分、地下鉄日比谷線の仲御徒町駅からもアクセスできます。",:sheet => "5",:info => "JR御徒町駅南口から徒歩2分の脱毛サロン・上野広小路店。白をベースにしたガーリーな雰囲気の漂うサロンは、パウダールームも完備。お出かけ前にツルすべ美肌に脱毛できちゃいます。ワキや顔はもちろん、VIO、全身脱毛も人気です。")
 Shopbranch.create!(:shopinfo_id => "2",:shopname => "銀座カラー",:branchname => "北千住店",:address => "東京都足立区千住3-1 ベニヤ第一ビル 3F",:tel => "",:starthour => "12:00",:endhour => "21:00",:e_starthour => "10:00",:e_endhour => "19:00",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "北千住",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "足立区",:access => "北千住駅西口から徒歩5分。駅を背にアーケードの商店街(きたろーど1010)を直進した先の、1階に美容室Ashがある、ベニヤ第一ビル3階です。",:sheet => "8",:info => "東京はもちろん、茨城や埼玉からのアクセスも便利な北千住店。駅前には大型ショッピングモールや大学もあり、活気にあふれたサロンです。全身脱毛の他にも、足脱毛や顔脱毛など人気部位の脱毛もお任せください。")
 Shopbranch.create!(:shopinfo_id => "2",:shopname => "銀座カラー",:branchname => "吉祥寺北口店",:address => "東京都武蔵野市吉祥寺本町1-4-15 ホワイトハウスビル 4F",:tel => "",:starthour => "12:00",:endhour => "21:00",:e_starthour => "10:00",:e_endhour => "19:00",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "吉祥寺",:train2 => "井の頭線",:station2 => "吉祥寺",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "武蔵野市",:access => "JR中央線・京王井の頭線の吉祥寺駅北口、ロータリーを正面に見て左方向へ徒歩1分、「ホワイトハウスビル」4階です。吉祥寺駅へは、新宿駅から中央線快速で15分、渋谷駅からは京王井の頭線急行で17分。",:sheet => "4",:info => "駅からのアクセスは徒歩１分！平日の仕事帰りでも、休日のショッピングや遊びついでにも通いやすい脱毛サロン・吉祥寺北口店。雨の日も気軽に通える近さがうれしい！顔脱毛、ワキ脱毛、VIO脱毛、お得な全身脱毛まで、気になる部分は脱毛で美肌をGETしましょう。")
 Shopbranch.create!(:shopinfo_id => "2",:shopname => "銀座カラー",:branchname => "立川店",:address => "東京都立川市柴崎町3-5-27 ＹＭビル 2F",:tel => "",:starthour => "12:00",:endhour => "21:00",:e_starthour => "10:00",:e_endhour => "19:00",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "立川",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "立川市",:access => "JR立川駅南口、グランデュオ立川より錦町方面へ徒歩2分、「YMビル」2階です。多摩モノレール立川南駅からも2番出口より徒歩2分。立川駅前の通いやすいサロンです。",:sheet => "6",:info => "アットホームな雰囲気が居心地がよいと好評の脱毛サロン・立川店。木の素材を取り入れたインテリアがあり、やさしく温もりのある空間です。駅から徒歩2分の通いやすさも魅力。お得な全身脱毛、人気のワキや顔、VIOコースなど、まずは無料カウンセリングをお気軽にどうぞ。")
 Shopbranch.create!(:shopinfo_id => "2",:shopname => "銀座カラー",:branchname => "立川北口店",:address => "東京都立川市曙町 1-14-14  メサビル 6F",:tel => "",:starthour => "12:00",:endhour => "21:00",:e_starthour => "10:00",:e_endhour => "19:00",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "立川",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "立川市",:access => "JR立川駅北口より曙町方面へ徒歩5分、「メサビル」の6階です。多摩モノレール立川北駅からも2番出口より徒歩2分。立川駅前の通いやすいサロンです。",:sheet => "10",:info => "明るく清潔感があり、ゆったり広い雰囲気の脱毛サロン・立川北口店。周辺には大型商業施設も多く、デートやショッピングのついでにも脱毛できちゃいます。お得な全身脱毛、人気の顔脱毛、ワキ脱毛、VIO脱毛など、まずはお気軽にご相談ください。")
 Shopbranch.create!(:shopinfo_id => "2",:shopname => "銀座カラー",:branchname => "八王子店",:address => "東京都八王子市三崎町4-11 トーネンビル 7F",:tel => "",:starthour => "12:00",:endhour => "21:00",:e_starthour => "10:00",:e_endhour => "19:00",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "八王子",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "八王子市",:access => "JR八王子駅北口より徒歩4分。北口改札を出てユーロードを直進。信号の手前左手のトーネンビル7階です。",:sheet => "9",:info => "アットホームな空間を大切にしている八王子店。癒しの時間の中で、全身脱毛、顔脱毛、VIO脱毛など、快適な施術をお楽しみいただけます。まずは無料カウンセリングを、お気軽にどうぞ。")
 Shopbranch.create!(:shopinfo_id => "2",:shopname => "銀座カラー",:branchname => "町田モディ店",:address => "東京都町田市原町田6-2-6 町田モディB2F",:tel => "",:starthour => "10:00",:endhour => "21:00",:e_starthour => "10:00",:e_endhour => "21:00",:holiday => "なし",:latitude => "",:longitude => "",:train => "JR線",:station => "町田",:train2 => "小田急線",:station2 => "町田",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "町田市",:access => "小田急町田駅西口すぐ、JR町田駅北口から徒歩3分、町田駅前通り沿い「町田モディ」B2階です。町田駅前の通いやすいサロンです。",:sheet => "8",:info => "小田急線町田駅西口すぐの脱毛サロン・町田モディ店。商業ビルの中にサロンがあるので、カフェやショッピングのついでに、気軽に立ち寄って脱毛できます。人気のワキ脱毛や顔脱毛はもちろん、女子力アップに欠かせないVIO脱毛、お得な全身脱毛もおすすめです。")
 Shopbranch.create!(:shopinfo_id => "3",:shopname => "脱毛ラボ",:branchname => "池袋西口店",:address => "東京都豊島区西池袋3-25-11 CIC IKEBUKUROBUIL9F",:tel => "0120-262-572",:starthour => "10:00",:endhour => "22:00",:e_starthour => "",:e_endhour => "",:holiday => "年中無休（1月1日〜3日除く)",:latitude => "",:longitude => "",:train => "JR線",:station => "池袋",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "豊島区",:access => "池袋西口を出ていただいて、一番左の信号を渡っていただきます。<br>ソフトバンクさんの角を曲がっていただいてまっすぐ進んでいただきます。左側には東京芸術劇場が見えて参ります。<br>しばらくすると、マクドナルドが見えて参ります。<br>信号が御座いますので渡っていただいて、マクドナルドを右手にしていただいて、また真っ直ぐ進んでいただきます。<br>ローソンが見えて参りますので、手前のビルの９階で御座います。<br>",:sheet => "施術ベッド9台（個室）",:info => "脱毛ラボ池袋西口店のご紹介<br><p>脱毛ラボは、お客様の肌や毛の状態に合わせて丁寧に脱毛いたします。 そのため、肌を傷つけることなく綺麗に仕上げることができます。 脱毛後の肌ケアについてもしっかりアドバイスさせえていただきます。 脱毛のことならば脱毛ラボ池袋西口店にお任せください。</p>")
 Shopbranch.create!(:shopinfo_id => "3",:shopname => "脱毛ラボ",:branchname => "銀座プレミアム店",:address => "東京都中央区銀座1-6-8 DEAR GINZA 5F",:tel => "0120-262-346",:starthour => "10:00",:endhour => "22:00",:e_starthour => "",:e_endhour => "",:holiday => "年中無休（1月1日〜3日除く)",:latitude => "",:longitude => "",:train => "有楽町線",:station => "銀座一丁目",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "中央区",:access => "東京メトロ有楽町線銀座一丁目駅6番出口を出ます。<br>右手方向にお進みいただき、最初の十字路を右折して下さい。<br>左側に「銀座イタリー亭」という飲食店があり、その隣の白い建物のビル、DEAR GINZAの5階です。",:sheet => "施術ベッド 9台（個室）",:info => "脱毛ラボが銀座に2店舗目をOPEN！！！<br><p>銀座で全身脱毛専門サロンをお探の方は「全国チェーンの安心性」「痛みがすくない」「リーズナブルな価格」の脱毛ラボ銀座プレミアム店へ。全身脱毛ならではの高い技術力で、お客様ひとりひとりの肌に合わせて施術をしています。</p>")
 Shopbranch.create!(:shopinfo_id => "3",:shopname => "脱毛ラボ",:branchname => "恵比寿店",:address => "東京都渋谷区恵比寿西1-10-7 MMSビル9F",:tel => "0120-262-889",:starthour => "10:00",:endhour => "22:00",:e_starthour => "",:e_endhour => "",:holiday => "年中無休（1月1日〜3日除く)",:latitude => "",:longitude => "",:train => "JR線",:station => "恵比寿",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "渋谷区",:access => "恵比寿駅4番出口をでて、恵比寿駅ロータリー方向に直進。<br>1階にひまわり薬局の入ったビルの9階です。",:sheet => "施術ベッド7台（個室）",:info => "脱毛ラボ恵比寿店は2012年9月1日にOPENしました！<br><p>恵比寿で全身脱毛専門サロンをお探の方は「全国チェーンの安心性」「痛みがすくない」「リーズナブルな価格」の脱毛ラボ恵比寿店へ。全身脱毛ならではの高い技術力で、お客様ひとりひとりの肌に合わせて施術をしています。</p>")
 Shopbranch.create!(:shopinfo_id => "3",:shopname => "脱毛ラボ",:branchname => "新宿店",:address => "東京都新宿区西新宿1-19-5 新宿幸容ビル8F",:tel => "0120-262-575",:starthour => "10:00",:endhour => "22:00",:e_starthour => "",:e_endhour => "",:holiday => "年中無休（1月1日〜3日除く)",:latitude => "",:longitude => "",:train => "JR線",:station => "新宿",:train2 => "小田急線",:station2 => "新宿",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "新宿区",:access => "JR線　新宿駅「南改札口」を出ます。※小田急線からお越しのお客様は小田急改札からJR改札口に出る道をご利用下さい。地下鉄をご利用の方は南口に出る道をご利用お願いします。<br>改札を出まして右に進みますと信号の先にファーストキッチンがありますので信号を渡って下さい。<br>信号を渡りましたらファーストキッチンを前にして左の脇を大通りに沿って、ヤマダ電機をこえて150メートル程お進み下さい。<br>ソフトバンクが１F に入ったビルの8Fになります。",:sheet => "施術ベッド9台（個室）",:info => "脱毛ラボ 新宿店は2014年6月21日にリニューアルオープンしました!!<br><p>新宿で全身脱毛専門サロンをお探の方は「全国チェーンの安心性」「痛みがすくない」「リーズナブルな価格」の脱毛ラボ新宿店へ。全身脱毛ならではの高い技術力で、お客様ひとりひとりの肌に合わせて施術をしています。</p>")
 Shopbranch.create!(:shopinfo_id => "3",:shopname => "脱毛ラボ",:branchname => "町田店",:address => "東京都町田市中町1-1-3 町田リラビル４F",:tel => "0120-262-287",:starthour => "10:00",:endhour => "22:00",:e_starthour => "",:e_endhour => "",:holiday => "年中無休（1月1日〜3日除く)",:latitude => "",:longitude => "",:train => "JR横浜線",:station => "町田",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "町田区",:access => "JR横浜線　町田駅「中央改札」を出ます。<br>改札を背にして右方向に進むと小田急線へと繋がる案内が出てくるので小田急改札方面へお越しください。<br>小田急改札が見えてきたら、「東口」出口へお進みください。<br>小田急線「東口」を出ますと左手に交番と踏切が見えてきますのでその踏切を渡ってください。<br>踏切を渡るとすぐ右手角に「りそな銀行」さんの大きなビルがあります。<br>「りそな銀行」さんのビルの隣が町田リラビルですので、エレベーターで４階に上がって頂くと脱毛ラボ町田店到着です。",:sheet => "施術ベッド8台（個室）",:info => "脱毛ラボ町田店のご紹介<br><p>町田で全身脱毛専門サロンをお探の方は「全国チェーンの安心性」「痛みがすくない」「リーズナブルな価格」の脱毛ラボ町田店へ。全身脱毛ならではの高い技術力で、お客様ひとりひとりの肌に合わせて施術をしています。</p>")
 Shopbranch.create!(:shopinfo_id => "3",:shopname => "脱毛ラボ",:branchname => "吉祥寺店",:address => "東京都武蔵野市吉祥寺本町1-13-10 アミノビル4階",:tel => "0120-262-167",:starthour => "10:00",:endhour => "22:00",:e_starthour => "",:e_endhour => "",:holiday => "年中無休（1月1日〜3日除く)",:latitude => "",:longitude => "",:train => "JR線",:station => "吉祥寺",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "武蔵野市",:access => "JR中央線。吉祥寺駅「中央（北口）」改札を出ます。<br>中央（北口）　出口の階段を下ります。<br>そのまま直進して頂くと、右手に交番がございますので、そちらを左折し、横断歩道を渡ってください。<br>渡って頂くと右手に「ヨドバシカメラ」。左手に「スターバックス」があります。<br>「スターバックス」を越えたところにある「ヨドバシカメラ」向かいペットショップがあるビルの4階です。",:sheet => "施術ベッド8台（個室）",:info => "脱毛ラボ吉祥寺店のご紹介<br><p>吉祥寺で全身脱毛専門サロンをお探の方は「全国チェーンの安心性」「痛みがすくない」「リーズナブルな価格」の脱毛ラボ吉祥寺店へ。全身脱毛ならではの高い技術力で、お客様ひとりひとりの肌に合わせて施術をしています。</p>")
 Shopbranch.create!(:shopinfo_id => "3",:shopname => "脱毛ラボ",:branchname => "立川店",:address => "東京都立川市柴崎町2-1-4 五光トミオー第2ビル7F",:tel => "0120-262-352",:starthour => "10:00",:endhour => "22:00",:e_starthour => "",:e_endhour => "",:holiday => "年中無休（1月1日〜3日除く)",:latitude => "",:longitude => "",:train => "JR線",:station => "立川",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "立川市",:access => "JR中央線・青梅線・南武線、立川駅　南口改札を出ます。<br>南口出口を出て、右方向に進んだところにある階段を下ります。<br>出口を背にして、左方向へお進み下さい。<br>左手に「マクドナルド」、右手に「メガネスーパー」がある通りを 100ｍほど直進してください。<br>お進み頂きましたら、右手に喫茶店「シャノアール」がございます。 そちらのビルの奥にあるエレベーターで７階へ上がって頂くと脱毛ラボ立川店です。 ※手前にもエレベーターがございますので、ご注意下さい。",:sheet => "施術ベッド8台（個室）",:info => "脱毛ラボ立川店のご紹介<br><p>立川で全身脱毛専門サロンをお探の方は「全国チェーンの安心性」「痛みがすくない」「リーズナブルな価格」の脱毛ラボ立川店へ。全身脱毛ならではの高い技術力で、お客様ひとりひとりの肌に合わせて施術をしています。</p>")
 Shopbranch.create!(:shopinfo_id => "3",:shopname => "脱毛ラボ",:branchname => "上野プレミアム店",:address => "東京都台東区上野4-5-5 455上野ビル7F",:tel => "0120-262-774",:starthour => "10:00",:endhour => "22:00",:e_starthour => "",:e_endhour => "",:holiday => "年中無休（1月1日〜3日除く)",:latitude => "",:longitude => "",:train => "JR線",:station => "上の",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "台東区",:access => "JR上野駅から不忍口よりヨドバシカメラを進行方向左側にし、直進します。<br>直進すると日拓エスパスがあり、更に直進するとABABがあります。<br>ABABを通り過ぎていくと、1階がauショップの入っているビルがあります。そこの7Fになります。",:sheet => "施術ベッド9台（個室）",:info => "脱毛ラボ上野プレミアム店のご紹介<br><p>脱毛ラボは、お客様の肌や毛の状態に合わせて丁寧に脱毛いたします。 そのため、肌を傷つけることなく綺麗に仕上げることができます。 脱毛後の肌ケアについてもしっかりアドバイスさせえていただきます。 脱毛のことならば脱毛ラボ上野プレミアム店にお任せください。</p>")
 Shopbranch.create!(:shopinfo_id => "3",:shopname => "脱毛ラボ",:branchname => "錦糸町店",:address => "東京都墨田区江東橋4-25-7 JU錦糸町ビル5F",:tel => "0120-262-014",:starthour => "10:00",:endhour => "22:00",:e_starthour => "",:e_endhour => "",:holiday => "年中無休（1月1日〜3日除く)",:latitude => "",:longitude => "",:train => "JR線",:station => "錦糸町",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "墨田区",:access => "JR錦糸町駅南口改札を出て、左に進みます。<br>横断歩道がありますので、正面LIVIN側に渡り右に進みます。<br>さらに横断歩道がありますので、みずほ銀行側に渡り左へ進みます。<br>一つ目の横断歩道を渡り（Patriotというパチンコ屋が見えます）、直進しますと右手に脱毛ラボの看板が見えます。<br>市進が入っているビルの５階になります。",:sheet => "施術ベッド7台（個室）",:info => "脱毛ラボ錦糸町店のご紹介<br><p>錦糸町で全身脱毛専門サロンをお探の方は「全国チェーンの安心性」「痛みがすくない」「リーズナブルな価格」の脱毛ラボ錦糸町店へ。全身脱毛ならではの高い技術力で、お客様ひとりひとりの肌に合わせて施術をしています。</p>")
 Shopbranch.create!(:shopinfo_id => "3",:shopname => "脱毛ラボ",:branchname => "五反田店",:address => "東京都品川区東五反田5-27-3 第二野村ビル6F",:tel => "0120-262-331",:starthour => "10:00",:endhour => "22:00",:e_starthour => "",:e_endhour => "",:holiday => "年中無休（1月1日〜3日除く)",:latitude => "",:longitude => "",:train => "JR線",:station => "五反田",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "品川区",:access => "五反田駅改札出て左側（ロータリー側）にユニクロ方面に向かいます。<br>ユニクロの隣に交番があるので向かいの信号をケンタッキー方面に渡っていただきます。<br>ケンタッキーの右隣3つ目のビル6Fです",:sheet => "施術ベッド9台（個室）",:info => "脱毛ラボ五反田店のご紹介<br><p>五反田で全身脱毛専門サロンをお探の方は「全国チェーンの安心性」「痛みがすくない」「リーズナブルな価格」の脱毛ラボ五反田店へ。全身脱毛ならではの高い技術力で、お客様ひとりひとりの肌に合わせて施術をしています。</p>")
 Shopbranch.create!(:shopinfo_id => "4",:shopname => "シースリー",:branchname => "北千住西口店",:address => "東京都足立区千住3-1 藤田ビル2F",:tel => "03-5284-2012",:starthour => "12:00",:endhour => "21:00",:e_starthour => "",:e_endhour => "",:holiday => "毎週水曜日・第2火曜日",:latitude => "",:longitude => "",:train => "JR線",:station => "北千住",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "足立区",:access => "JR北千住駅から徒歩5分",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "4",:shopname => "シースリー",:branchname => "錦糸町店",:address => "東京都墨田区江東橋4-10-2 コリンズ16ビル7F",:tel => "03-5625-3307",:starthour => "12:00",:endhour => "21:00",:e_starthour => "",:e_endhour => "",:holiday => "毎週水曜日・第2火曜日",:latitude => "",:longitude => "",:train => "JR線",:station => "錦糸町",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "墨田区",:access => "ＪＲ錦糸町駅徒歩5分",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "4",:shopname => "シースリー",:branchname => "PR成増店",:address => "東京都板橋区成増1-13-15 BMRビル2F",:tel => "03-5968-5681",:starthour => "12:00",:endhour => "21:00",:e_starthour => "",:e_endhour => "",:holiday => "毎週水曜日・第2火曜日",:latitude => "",:longitude => "",:train => "東武東上線",:station => "成増",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "板橋区",:access => "東武東上線成増駅南口から徒歩3分",:sheet => "",:info => "")
 Shopbranch.create!(:shopinfo_id => "4",:shopname => "シースリー",:branchname => "PR葛西店",:address => "東京都江戸川区中葛西3-37-3 志美津ビル6Ｆ",:tel => "03-5667-5102",:starthour => "12:00",:endhour => "21:00",:e_starthour => "",:e_endhour => "",:holiday => "毎週水曜日・第2火曜日",:latitude => "",:longitude => "",:train => "JR線",:station => "葛西",:train2 => "",:station2 => "",:train3 => "",:station3 => "",:area => "関東",:prefec => "東京都",:city => "江戸川区",:access => "JR葛西駅中央口から徒歩2分",:sheet => "",:info => "")

 Shopfb.create!(:shopinfo_id => "1",:fbshopname => "ミュゼプラチナム",:fbtitle => "お得意様",:fbcomment => "価格の推移をずっと見てきましたが、今回かなり下がったので購入しました。
 私は首のコリが酷いため、効果があればと思い購入しました。",:auther => "hebochi",:fbrank => 4,:ages => "20代前半",:jobs => "OL")
 Shopfb.create!(:shopinfo_id => "1",:fbshopname => "ミュゼプラチナム",:fbtitle => "気持ちぃぃ",:fbcomment => "首こりがひどかったのですが、これを使用することで、大変楽になりました。
 とってもいい買い物ができたと思います。",:auther => "スリーパー",:fbrank => 5,:ages => "30代前半",:jobs => "OL")
 Shopfb.create!(:shopinfo_id => "1",:fbshopname => "ミュゼプラチナム",:fbtitle => "おすすめです",:fbcomment => "価格の推移をずっと見てきましたが、今回かなり下がったので購入しました。
 私は首のコリが酷いため、効果があればと思い購入しました。",:auther => "よしこ",:fbrank => 4,:ages => "30代前半",:jobs => "OL")
 Shopfb.create!(:shopinfo_id => "2",:fbshopname => "銀座カラー",:fbtitle => "安くてよかった",:fbcomment => "首こりがひどかったのですが、これを使用することで、大変楽になりました。
 とってもいい買い物ができたと思います。",:auther => "Customer",:fbrank => 3,:ages => "20代後半",:jobs => "OL")
 Shopfb.create!(:shopinfo_id => "2",:fbshopname => "銀座カラー",:fbtitle => "勧誘がなかった",:fbcomment => "価格の推移をずっと見てきましたが、今回かなり下がったので購入しました。
 私は首のコリが酷いため、効果があればと思い購入しました。",:auther => "ユーザー",:fbrank => 4,:ages => "20代後半",:jobs => "OL")
 Shopfb.create!(:shopinfo_id => "2",:fbshopname => "銀座カラー",:fbtitle => "お財布に優しい",:fbcomment => "首こりがひどかったのですが、これを使用することで、大変楽になりました。
 とってもいい買い物ができたと思います。",:auther => "Beauty",:fbrank => 5,:ages => "10代後半",:jobs => "学生")
 Shopfb.create!(:shopinfo_id => "3",:fbshopname => "脱毛ラボ",:fbtitle => "気遣いが素晴らしい",:fbcomment => "価格の推移をずっと見てきましたが、今回かなり下がったので購入しました。
 私は首のコリが酷いため、効果があればと思い購入しました。",:auther => "たらこ",:fbrank => 5,:ages => "20代後半",:jobs => "ショップ店員")
 Shopfb.create!(:shopinfo_id => "3",:fbshopname => "脱毛ラボ",:fbtitle => "勧誘なし！",:fbcomment => "首こりがひどかったのですが、これを使用することで、大変楽になりました。
 とってもいい買い物ができたと思います。",:auther => "山田花子",:fbrank => 5,:ages => "30代前半",:jobs => "美容関係")
 Shopfb.create!(:shopinfo_id => "3",:fbshopname => "脱毛ラボ",:fbtitle => "寝てしまった",:fbcomment => "価格の推移をずっと見てきましたが、今回かなり下がったので購入しました。
 私は首のコリが酷いため、効果があればと思い購入しました。",:auther => "まゆみん",:fbrank => 4,:ages => "30代後半",:jobs => "ショップ店員")
 Shopfb.create!(:shopinfo_id => "4",:fbshopname => "シースリー",:fbtitle => "おすすめできるかな",:fbcomment => "首こりがひどかったのですが、これを使用することで、大変楽になりました。
 とってもいい買い物ができたと思います。",:auther => "りさりさ",:fbrank => 5,:ages => "20代前半",:jobs => "OL")
 Shopfb.create!(:shopinfo_id => "4",:fbshopname => "シースリー",:fbtitle => "大満足",:fbcomment => "価格の推移をずっと見てきましたが、今回かなり下がったので購入しました。
 私は首のコリが酷いため、効果があればと思い購入しました。",:auther => "Hirokomix",:fbrank => 4,:ages => "20代後半",:jobs => "OL")
