require "csv"
CSV.foreach('musee.csv') do |row|
 print "Shopbranch.create!("
 print ":shopinfo_id => " + %Q["#{row[0]}"]
 print ",:shopname => " + %Q["#{row[1]}"]
 print ",:branchname => " + %Q["#{row[2]}"]
 print ",:address => " + %Q["#{row[3]}"]
 print ",:tel => " + %Q["#{row[4]}"]
 print ",:starthour => " + %Q["#{row[5]}"]
 print ",:endhour => " + %Q["#{row[6]}"]
 print ",:e_starthour => " + %Q["#{row[7]}"]
 print ",:e_endhour => " + %Q["#{row[8]}"]
 print ",:holiday => " + %Q["#{row[9]}"]
 print ",:latitude => " + %Q["#{row[10]}"]
 print ",:longitude => " + %Q["#{row[11]}"]
 print ",:train => " + %Q["#{row[12]}"]
 print ",:station => " + %Q["#{row[13]}"]
 print ",:train2 => " + %Q["#{row[14]}"]
 print ",:station2 => " + %Q["#{row[15]}"]
 print ",:train3 => " + %Q["#{row[16]}"]
 print ",:station3 => " + %Q["#{row[17]}"]
 print ",:area => " + %Q["#{row[18]}"]
 print ",:prefec => " + %Q["#{row[19]}"]
 print ",:city => " + %Q["#{row[20]}"]
 print ",:access => " + %Q["#{row[21]}"]
 print ",:sheet => " + %Q["#{row[22]}"]
 print ",:info => " + %Q["#{row[23]}"]
 print ")\n"
end
CSV.foreach('ginza.csv') do |row|
 print "Shopbranch.create!("
 print ":shopinfo_id => " + %Q["#{row[0]}"]
 print ",:shopname => " + %Q["#{row[1]}"]
 print ",:branchname => " + %Q["#{row[2]}"]
 print ",:address => " + %Q["#{row[3]}"]
 print ",:tel => " + %Q["#{row[4]}"]
 print ",:starthour => " + %Q["#{row[5]}"]
 print ",:endhour => " + %Q["#{row[6]}"]
 print ",:e_starthour => " + %Q["#{row[7]}"]
 print ",:e_endhour => " + %Q["#{row[8]}"]
 print ",:holiday => " + %Q["#{row[9]}"]
 print ",:latitude => " + %Q["#{row[10]}"]
 print ",:longitude => " + %Q["#{row[11]}"]
 print ",:train => " + %Q["#{row[12]}"]
 print ",:station => " + %Q["#{row[13]}"]
 print ",:train2 => " + %Q["#{row[14]}"]
 print ",:station2 => " + %Q["#{row[15]}"]
 print ",:train3 => " + %Q["#{row[16]}"]
 print ",:station3 => " + %Q["#{row[17]}"]
 print ",:area => " + %Q["#{row[18]}"]
 print ",:prefec => " + %Q["#{row[19]}"]
 print ",:city => " + %Q["#{row[20]}"]
 print ",:access => " + %Q["#{row[21]}"]
 print ",:sheet => " + %Q["#{row[22]}"]
 print ",:info => " + %Q["#{row[23]}"]
 print ")\n"
end
CSV.foreach('lab.csv') do |row|
 print "Shopbranch.create!("
 print ":shopinfo_id => " + %Q["#{row[0]}"]
 print ",:shopname => " + %Q["#{row[1]}"]
 print ",:branchname => " + %Q["#{row[2]}"]
 print ",:address => " + %Q["#{row[3]}"]
 print ",:tel => " + %Q["#{row[4]}"]
 print ",:starthour => " + %Q["#{row[5]}"]
 print ",:endhour => " + %Q["#{row[6]}"]
 print ",:e_starthour => " + %Q["#{row[7]}"]
 print ",:e_endhour => " + %Q["#{row[8]}"]
 print ",:holiday => " + %Q["#{row[9]}"]
 print ",:latitude => " + %Q["#{row[10]}"]
 print ",:longitude => " + %Q["#{row[11]}"]
 print ",:train => " + %Q["#{row[12]}"]
 print ",:station => " + %Q["#{row[13]}"]
 print ",:train2 => " + %Q["#{row[14]}"]
 print ",:station2 => " + %Q["#{row[15]}"]
 print ",:train3 => " + %Q["#{row[16]}"]
 print ",:station3 => " + %Q["#{row[17]}"]
 print ",:area => " + %Q["#{row[18]}"]
 print ",:prefec => " + %Q["#{row[19]}"]
 print ",:city => " + %Q["#{row[20]}"]
 print ",:access => " + %Q["#{row[21]}"]
 print ",:sheet => " + %Q["#{row[22]}"]
 print ",:info => " + %Q["#{row[23]}"]
 print ")\n"
end
CSV.foreach('ccc.csv') do |row|
 print "Shopbranch.create!("
 print ":shopinfo_id => " + %Q["#{row[0]}"]
 print ",:shopname => " + %Q["#{row[1]}"]
 print ",:branchname => " + %Q["#{row[2]}"]
 print ",:address => " + %Q["#{row[3]}"]
 print ",:tel => " + %Q["#{row[4]}"]
 print ",:starthour => " + %Q["#{row[5]}"]
 print ",:endhour => " + %Q["#{row[6]}"]
 print ",:e_starthour => " + %Q["#{row[7]}"]
 print ",:e_endhour => " + %Q["#{row[8]}"]
 print ",:holiday => " + %Q["#{row[9]}"]
 print ",:latitude => " + %Q["#{row[10]}"]
 print ",:longitude => " + %Q["#{row[11]}"]
 print ",:train => " + %Q["#{row[12]}"]
 print ",:station => " + %Q["#{row[13]}"]
 print ",:train2 => " + %Q["#{row[14]}"]
 print ",:station2 => " + %Q["#{row[15]}"]
 print ",:train3 => " + %Q["#{row[16]}"]
 print ",:station3 => " + %Q["#{row[17]}"]
 print ",:area => " + %Q["#{row[18]}"]
 print ",:prefec => " + %Q["#{row[19]}"]
 print ",:city => " + %Q["#{row[20]}"]
 print ",:access => " + %Q["#{row[21]}"]
 print ",:sheet => " + %Q["#{row[22]}"]
 print ",:info => " + %Q["#{row[23]}"]
 print ")\n"
end
